server:
  host: 0.0.0.0
  port: 8080
  
vadek:
  mode: "development"
  work_dir: "./" 
  log_dir: "./logs" 

logging:
  filename: log.log
  level:
    app: info 
    gorm: warn 
  maxsize: 10 
  maxage: 30
  compress: false 

sqlite3:
  enable: true

mysql:
  host: 127.0.0.1
  port: 3306
  db: 
  username: 
  password: 


